Module11 task1
htmlacademy-javascript/1826213-keksobooking-26 pull request #10
Opened 2022-07-11 15:19 UTC by Denysmogyliuk

2022-07-12 23:13 UTC, Ch1sKey requested changes

2022-07-12 23:13 UTC, Ch1sKey commented on js/api.js
> +      unblockSubmitButton();
Немного не консистентно разблокировать кнопку в одном месте, а блокировать в другом. Я бы предложил функцию blockSubmitButton вызывать в начале запроса

2022-07-12 23:13 UTC, Ch1sKey commented on js/api.js
> +    }).finally(() => {
Не думаю, что нужно дублировать логику ошибок. Если контроль не попадает в блок `catch`, то ошибки и не будет. По крайней мере, если бекенд правильно настроен

2022-07-12 23:13 UTC, Ch1sKey commented on js/utils.js
> +
В index.html вроде бы уже есть шаблон для блока с ошибками. Почему бы не использовать его?

2022-07-13 11:20 UTC, Denysmogyliuk commented on js/utils.js
> +
Прост в ТЗ написали придумать дизайн самому, но да, логично)

2022-07-13 19:23 UTC, Ch1sKey commented on js/map.js
>    },
Можно уж стразу заменить весь объект на INITIAL_COORDINATES.

`const mainPinMarker = L.marker(INITIAL_COORDINATES)`

2022-07-13 19:23 UTC, Ch1sKey commented on js/map.js
> +      lng: INITIAL_COORDINATES.lng,
И тут

2022-07-13 19:24 UTC, merged